source 'https://github.com/redspark-io/redspark-ios-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'miguelopolis' do

    # Internal libs
    pod 'RSStarterKit'
    pod 'RSWidgets'
    pod 'Kingfisher', '~> 3.2.1'
    pod 'SlideMenuControllerSwift', '~> 3.0.0'
    pod 'Kingfisher', '~> 3.0'
    
end
