export const EMPRESA_POST_ERROR = 'POST_EMPRESA_ERROR';
export const EMPRESA_POST_DATA = 'POST_EMPRESA_DATA';
export const EMPRESA_POST_OK = 'POST_EMPRESA_OK';

export const EMPRESA_PUT_ERROR = 'PUT_EMPRESA_ERROR';
export const EMPRESA_PUT_DATA = 'PUT_EMPRESA_DATA';
export const EMPRESA_PUT_OK = 'PUT_EMPRESA_OK';

export const EMPRESA_REQUEST_ERROR = 'REQUEST_EMPRESA_ERROR';
export const EMPRESA_REQUEST_DATA = 'REQUEST_EMPRESA_DATA';
export const EMPRESA_REQUEST_OK = 'REQUEST_EMPRESA_OK';

export const TEMPLATE_REQUEST_ERROR = 'REQUEST_TEMPLATE_ERROR';
export const TEMPLATE_REQUEST_DATA = 'REQUEST_TEMPLATE_DATA';
export const TEMPLATE_REQUEST_OK = 'REQUEST_TEMPLATE_OK';

export const TEMPLATE_POST_ERROR = 'POST_TEMPLATE_ERROR';
export const TEMPLATE_POST_DATA = 'POST_TEMPLATE_DATA';
export const TEMPLATE_POST_OK = 'POST_TEMPLATE_OK';

export const EMPRESA_TEMPLATE_REQUEST_ERROR = 'REQUEST_EMPRESA_TEMPLATE_ERROR';
export const EMPRESA_TEMPLATE_REQUEST_DATA = 'REQUEST_EMPRESA_TEMPLATE_DATA';
export const EMPRESA_TEMPLATE_REQUEST_OK = 'REQUEST_EMPRESA_TEMPLATE_OK';